### ISSUE TITLE
Clicking an entry in Inventory leads to a 404 page to sales rep

### ISSUE THREAD

**Issue by qandeelarshad** [purplesmurf1998/Autotracks#104] opened 2022-03-23 17:23 UTC
### Description
When logged in as a sales rep, clicking any entry in the inventory list of vehicles redirects to a 404 page. 

### Steps to reproduce
1. Login with sales rep account
2. Click on Inventory in the sidebar
3. Click on any entry in the inventory table
4. A redirect to a 404 page will occur.

### Screenshots
![snip1](https://user-images.githubusercontent.com/60014879/159758909-54c17088-a20c-4316-9406-6e1063ccb626.PNG)
![snip2](https://user-images.githubusercontent.com/60014879/159758925-4ec6007a-2e8a-4a01-9fbc-b17740bc13ed.PNG)

**Comment by purplesmurf1998** [comment] 2022-03-23 23:48
Will check this out, seems to be a forbidden access problem being thrown in the backend API

**Comment by purplesmurf1998** [comment] 2022-03-23 23:55
@AbdulSir the problem is that the VehicleDetails page is fetching dealership users and the route is protected for users with role 'Administration' and 'Management'. I've removed the check "hasPermissions" since I think everyone should be able to fetch the dealership users. Let me know what you think.

**Comment by AbdulSir** [comment] 2022-03-24 01:03
> @AbdulSir the problem is that the VehicleDetails page is fetching dealership users and the route is protected for users with role 'Administration' and 'Management'. I've removed the check "hasPermissions" since I think everyone should be able to fetch the dealership users. Let me know what you think.

@purplesmurf1998 Thanks for looking into it. Yes, indeed that seems to be the issue. It has been fixed now as you have suggested. I don't foresee any security concern if we increase the role access for the getUsers route.

@qandeelarshad Thanks for flagging this issue. it has been addressed now.

**Closed by AbdulSir** 2022-03-24 01:03 UTC
Labels: bug
