### ISSUE TITLE
As either Sales Rep or Admin, "sell vehicle" button does not appear and transaction cannot be created.

### ISSUE THREAD

**Issue by AdrienKamran** [purplesmurf1998/Autotracks#111] opened 2022-03-30 22:28 UTC
When logged in as a sales rep or an admin, the option to sell a vehicle in the vehicle details modal does not appear.

![image](https://user-images.githubusercontent.com/50927558/160941475-604242b9-1b13-4804-bcc5-49767cf3709a.png)

**Comment by purplesmurf1998** [comment] 2022-03-31 20:57
This is not a bug, the vehicle has actually already been sold hence why we see the `Marks as delivered` option instead. Since a vehicle can't be sold twice, the option is removed.

Will close this issue since there is nothing to fix

**Closed by purplesmurf1998** 2022-03-31 20:57 UTC
Labels: bug

**Comment by AdrienKamran** [comment] 2022-04-01 03:04
> This is not a bug, the vehicle has actually already been sold hence why we see the `Marks as delivered` option instead. Since a vehicle can't be sold twice, the option is removed.
> 
> Will close this issue since there is nothing to fix

Thank you for the quick reply, this was an oversight on my part. Everything works as expected!
